ENH: cleanup
this is the basic initial take to address #39

dciodvfy checks for the SR object generated by the test produces the following output:

```
$ ./DicomSRValidator.sh /Users/fedorov/local/builds/dcmqi-superbuild/dcmqi-build/bin/sr-tid1500-example.dcm
Found EnhancedSR IOD
Found Root Template TID_1500 (MeasurementReport)
Error: Template 1204 LanguageOfContentItemAndDescendants/[Row 1] CODE (121049,DCM,"Language of Content Item and Descendants"): 1.1: /CONTAINER (126000,DCM,"Imaging Measurement Report")/CODE (121049,DCM,"Language of Content Item and Descendants"): Code (eng,RFC5646,"English") not found in context group 5000
Error: Template 1500 MeasurementReport/[Row 1] CONTAINER CID 7021/[Row 4] CODE (121058,DCM,"Procedure reported"): 1.4: /CONTAINER (126000,DCM,"Imaging Measurement Report")/CODE (121058,DCM,"Procedure reported"): Code (P0-0099A,SRT,"Imaging procedure") not found in context group 100
Warning: Template 1411 VolumetricROIMeasurements/[Row 1] CONTAINER (125007,DCM,"Measurement Group")/[Row 12] UIDREF (121232,DCM,"Source series for image segmentation"): 1.6.1.5: /CONTAINER (126000,DCM,"Imaging Measurement Report")/CONTAINER (126010,DCM,"Imaging Measurements")/CONTAINER (125007,DCM,"Measurement Group")/UIDREF (121232,DCM,"Source series for segmentation"): Code (121232,DCM,"Source series for segmentation") has different code meaning ("Source series for segmentation") than code meaning in template concept name ("Source series for image segmentation")
Root Template Validation Complete
IOD validation complete
```

First error is due to a pending CP http://www.dclunie.com/dicom-status/status.html#CP1567,
the code used is the right one suggested by @dclunie

Second error is due to an issue in the validator, @dclunie will fix it -
it should be a warning instead.

Third warning is an incorrect code used in the validator, @dclunie will
fix it there.