ci: Add missing checkout comment to CircleCI deploy-* jobs
This commit fixes the following error:

  RuntimeError: Current directory is expected to be inside a git working tree: /home/circleci/project